language: java
sudo: false
script: mvn install
before_deploy
- git config --local user.name "Eaglestriker"
- git config --local user.email "dubath.tim@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date + '%Y%m%d%H%M%S')-$(git log --format=%h -1)}
-git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: uZXUxoRPv398peLQZrxQ+/MeeBqOVboQDtE0Jl3EmsSf019++AhqsL2gnfmbDsvEILyuVqL0h8+Y4xTZd8PucC5cdBNY5TeD/3VoZdySAQNni6z3KBq8ZERLKYeJVl/RfLjSqCPk690wXxRyqOQLm2GyVqZLM7TFMoVbxyAR5Gpo9V+HtTUi+X+J+VyxYRMid8UkAJ2PYPZRXhzrZX4QzwbdES2fxy8on7W0XZCvmXZVUe7dkt5gfbwWPlLuKhn76v5R9K/7OF5HNHDDOv6bA92+Mb8qnsu5U2VAapcC4dxQhc/wFqi2+GFMXm+wEZkQ562iQnyJh6L6pO14tEjqUHP3a+cGzzAb5isWbbjOVg3r01NDmBvvuHeaT4TerRoVOltC0WVhmLv/Hte78peDxOH/ozX1amHaTJnjuwbo/ii/Q6fGNWYEcEhr42KaPl7bjoQD7VVaC4I1lzAZa/CEIbYZG9L4jrSoBCScek+kbkF9IxF+QerPfACXXnkfn4P264MZvglOw68+sLog/TWM6ow3BFhs7529OUjoFw6fUQxksKANYX1M/A3MmezBr13Fcs2RiTUqdcpjKVfDcnsWmvGa7EqtxMh8GqL4Wd8DXKr/hI1FisGF/yMTFRci5bBgcdvccRNmmHimWUwCKx7/hoLM+XmqjMQReRmfB7jrkCo=
  file: "/home/travis/.m2/repository/ch/bbw/td/02_ConsoleCalculatorWithMaven3/0.0.1-SNAPSHOT/02_ConsoleCalculatorWithMaven3-0.0.1-SNAPSHOT.jar"
  on:
    repo: Eaglestriker/ConsoleCalculatorWithMaven2

